config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gauntlet.users.urls", namespace="users")),
    path("matches/", include("gauntlet.matches.urls", namespace="matches")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gauntlet/matches/urls.py
from django.urls import path

from gauntlet.matches.views import TournamentDetailView, TournamentListView, new_freeplay, new_planned, show_scores

app_name = "matches"

urlpatterns = [
    path("new/freeplay/", new_freeplay, name="new_freeplay"),
    path("new/planned/<int:id>/", new_planned, name="new_planned"),
    path("scores/", show_scores, name="show_scores"),
    path("tournaments/", TournamentListView.as_view(), name="tournaments"),
    path("tournaments/<int:pk>/", TournamentDetailView.as_view(), name="tournament-detail"),
]

gauntlet/users/urls.py
from django.urls import path

from gauntlet.users.views import user_redirect_view

app_name = "users"
urlpatterns = []

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<int:pk>/", view=user_detail_view, name="detail"),
]

gauntlet/matches/models.py
import itertools
from enum import Enum

import pandas as pd
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

User = get_user_model()


class MatchQuerySet(models.QuerySet):
    def with_player(self, player):
        return self.filter(models.Q(player_1=player) | models.Q(player_2=player))

    def without_player(self, player):
        return self.filter(~models.Q(player_1=player) & ~models.Q(player_2=player))

    def with_players(self, player_1, player_2):
        return self.filter(
            models.Q(player_1=player_1, player_2=player_2) | models.Q(player_1=player_2, player_2=player_1)
        )


class Match(models.Model):
    player_1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="match_player_1")
    player_2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="match_player_2")
    score_player_1 = models.PositiveSmallIntegerField(null=True)
    score_player_2 = models.PositiveSmallIntegerField(null=True)
    round_scores = models.JSONField(null=True)
    date = models.DateField(default=timezone.now)

    objects = MatchQuerySet.as_manager()

    class Meta:
        verbose_name_plural = "matches"

    def __str__(self):
        s = f"Match: {self.player_1}/{self.player_2} "
        s += f"Score: {self.score_player_1}:{self.score_player_2}"
        return s


# TODO just set the name of the user to the email sans domain and get rid of this helper
def get_user_name(user):
    return user.email.split("@")[0]


class Tournament(models.Model):
    class State(Enum):
        PLANNED = 1
        ONGOING = 2
        FINISHED = 3

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, null=True, blank=True)
    players = models.ManyToManyField(User, blank=True)
    state = models.SmallIntegerField(default=State.PLANNED.value)

    def removePlayer(self, player):
        if self.state != self.State.PLANNED.value:
            raise Exception("This tournament is not in the planning phase")
        if player not in self.players.all():
            raise Exception("Player already not signed up for this tournament")
        self.players.remove(player)
        self.save()

    def addPlayer(self, player):
        if self.state != self.State.PLANNED.value:
            raise Exception("This tournament is not in the planning phase")
        if player in self.players.all():
            raise Exception("Player already signed up for this tournament")
        self.players.add(player)
        self.save()

    def start(self):
        if self.state != self.State.PLANNED.value:
            raise Exception("This tournament is not in the planning phase")
        if self.players.count() < 2:
            raise Exception("Not enough players!")
        combinations = list(itertools.combinations(self.players.all(), 2))
        for player_pair in combinations:
            PlannedMatch.objects.create(player_1=player_pair[0], player_2=player_pair[1], tournament=self)
        self.state = self.State.ONGOING.value
        self.save()

    def get_boards(self):
        played_matches = [p.actual_match for p in self.planned_matches.played()]
        player_names = [get_user_name(user) for user in self.players.all()]

        scoreboard = self.get_scoreboard(played_matches, player_names)
        leaderboard = self.get_leaderboard(played_matches, player_names)
        return scoreboard, leaderboard

    def get_leaderboard(self, played_matches, player_names):
        leaderboard = pd.DataFrame(0, player_names, ["Wins", "Matches", "Sets lost"])
        for match in played_matches:
            name_1 = get_user_name(match.player_1)
            name_2 = get_user_name(match.player_2)
            score_1 = match.score_player_1
            score_2 = match.score_player_2

            leaderboard.at[name_1, "Matches"] += 1
            leaderboard.at[name_2, "Matches"] += 1
            if score_1 > score_2:
                leaderboard.at[name_1, "Wins"] += 1
            elif score_2 > score_1:
                leaderboard.at[name_2, "Wins"] += 1
            for score in match.round_scores:
                if score[0] < score[1]:
                    leaderboard.at[name_1, "Sets lost"] += 1
                elif score[0] > score[1]:
                    leaderboard.at[name_2, "Sets lost"] += 1

        leaderboard.sort_values(by=["Wins", "Matches", "Sets lost"], inplace=True, ascending=[False, True, True])
        return leaderboard

    def get_scoreboard(self, played_matches, player_names):
        scoreboard = pd.DataFrame("-", player_names, player_names)
        for match in played_matches:
            name_1 = get_user_name(match.player_1)
            name_2 = get_user_name(match.player_2)
            score_1 = match.score_player_1
            score_2 = match.score_player_2

            scoreboard.at[name_2, name_1] = f"{score_2}:{score_1}"
            scoreboard.at[name_1, name_2] = f"{score_1}:{score_2}"
        return scoreboard

    def isInPlanning(self):
        return self.state == self.State.PLANNED.value

    def isOngoing(self):
        return self.state == self.State.ONGOING.value

    def isFinished(self):
        return self.state == self.State.FINISHED.value


class PlannedMatchQuerySet(MatchQuerySet):
    def played(self):
        return self.filter(~models.Q(actual_match=None))

    def not_played(self):
        return self.filter(actual_match=None)


class PlannedMatch(models.Model):
    player_1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="planned_match_player_1")
    player_2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="planned_match_player_2")
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, related_name="planned_matches")
    actual_match = models.ForeignKey(Match, on_delete=models.SET_NULL, null=True, blank=True)

    objects = PlannedMatchQuerySet.as_manager()

    class Meta:
        verbose_name_plural = "planned_matches"

    def __str__(self):
        s = f"PlannedMatch: {self.player_1}/{self.player_2}"
        return s

gauntlet/matches/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Match

User = get_user_model()

MAX_ROUNDS_PER_MATCH = 8
INITIAL_ROUNDS_PER_MATCH = 5
MIN_ROUND_SCORE = 11


class BasePartialForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True

        # TODO move styling out of backend code
        self.helper.form_style = "inline"
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-sm-4 col-lg-2"
        self.helper.field_class = "col-sm-8 col-lg-4"
        self.helper.css_class = "border border-secondary rounded p-3 my-3 col-md-6"


class DateForm(BasePartialForm):
    date = forms.DateField(initial=timezone.now, required=True)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get("date") > timezone.now().date():
            raise ValidationError(["You cannot add a match played in the future"])
        return cleaned_data


class OpponentForm(BasePartialForm):
    opponent = forms.ModelChoiceField(queryset=User.objects.order_by("email"), required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields["opponent"].queryset = User.objects.order_by("email").exclude(id=self.user.id)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data["opponent"] == self.user:
            raise ValidationError(["You cannot play against yourself"])
        return cleaned_data


class RoundCountForm(BasePartialForm):
    round_count = forms.IntegerField(
        min_value=1, max_value=MAX_ROUNDS_PER_MATCH, required=False, initial=INITIAL_ROUNDS_PER_MATCH
    )

    def save(self, score_player_1, score_player_2, round_scores):
        data = self.clean()
        if data["player_1"].email < data["player_2"].email:
            match = Match(
                player_1=data["player_1"],
                player_2=data["player_2"],
                score_player_1=score_player_1,
                score_player_2=score_player_2,
                round_scores=round_scores,
                date=data["date"],
            )
        else:
            match = Match(
                player_1=data["player_2"],
                player_2=data["player_1"],
                score_player_1=score_player_2,
                score_player_2=score_player_1,
                round_scores=[list(reversed(r)) for r in round_scores],
                date=data["date"],
            )
        match.save()
        return match


class BaseRoundFormSet(forms.BaseFormSet):
    # The returned scores assume player_1 is the active user,
    # unless reverse was set to True.
    def get_scores(self, round_count, reverse=False):
        def calculate_winner_score(loser_score):
            if loser_score < 10:
                return 11
            return loser_score + 2

        if any(self.errors):
            return
        scores = {
            "player_1": 0,
            "player_2": 0,
            "rounds": [],
        }
        print(round_count)
        for i in range(round_count):
            form = self.forms[i]
            score_loser = form.cleaned_data["score_loser"]
            player_1_won = form.cleaned_data["player_1_won"]
            if (player_1_won and not reverse) or (not player_1_won and reverse):
                scores["player_1"] += 1
                scores["rounds"].append([calculate_winner_score(score_loser), score_loser])
            else:
                scores["player_2"] += 1
                scores["rounds"].append([score_loser, calculate_winner_score(score_loser)])
        return scores


class RoundForm(forms.Form):
    player_1_won = forms.BooleanField(required=False)
    score_loser = forms.IntegerField(min_value=0, max_value=100, label="Loser score")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Field("player_1_won", type="hidden"),
            Field("score_loser"),
        )
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-3"
        self.helper.field_class = "col-9"
        self.initial["player_1_won"] = "true"

    def get_formset_factory():
        # TODO this creates the max amount of round forms, which are then conditionally
        # hidden on the frontend. Rather, the frontend should dynamically create and delete
        # forms as necessary
        return forms.formset_factory(
            RoundForm,
            formset=BaseRoundFormSet,
            extra=MAX_ROUNDS_PER_MATCH,
            min_num=1,
            max_num=MAX_ROUNDS_PER_MATCH,
            absolute_max=MAX_ROUNDS_PER_MATCH,
            validate_min=True,
            validate_max=True,
        )

gauntlet/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

gauntlet/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

gauntlet/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import RedirectView

User = get_user_model()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

gauntlet/templates/matches/new_base.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" media="all">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    {% block match_headline %}
    {% endblock %}
    <form method="post">
        {% csrf_token %}
        {% crispy date_form %}
        {% block players %}
        {% endblock %}
        {% crispy round_count_form %}
        <h4>Round scores:</h4>
        {{ rounds_formset.management_form|crispy }}
        {% for form in rounds_formset %}
        <div class="border border-secondary rounded p-3 my-3 col-lg-6 col-12" id="div_outer_round_formset_{{ forloop.counter0 }}">
            <div id="div_id_rounds-{{ forloop.counter0 }}-player_1_won_button" class="mb-3 row">
                <label for="id_rounds-{{ forloop.counter0 }}-player_1_won_button" class="col-form-label col-3">
                    You
                </label>
                <div class="col-9">
                    <button type="button" class="btn w-100 active text-start" id="id_rounds-{{ forloop.counter0 }}-player_1_won_button">WON</button>
                </div>
            </div>
            {% crispy form %}
            <div id="div_id_rounds-{{ forloop.counter0 }}-score_winner" class="mb-3 row"> <label for="id_rounds-{{ forloop.counter0 }}-score_winner" class="col-form-label col-3 requiredField">
                Winner score </label> <div class="col-9"> <input type="number" name="rounds-{{ forloop.counter0 }}-score_winner" value="11" min="0" max="100" required="False" readonly="True" class="numberinput form-control" id="id_rounds-{{ forloop.counter0 }}-score_winner"> </div> </div>
            </div>
        {% endfor %}
        <input type="submit" value="Submit" class="mb-3">
    </form>

    <script>
        const MAX_ROUNDS_PER_MATCH = 8;

        // Hides surplus round sub-forms
        function roundsCallback() {
            var rounds = document.getElementById("id_round_count").value;
            for (let i = 0; i < MAX_ROUNDS_PER_MATCH; i++) {
                enabled = i+1 <= rounds
                document.getElementById("id_rounds-" + i + "-score_loser").required = enabled ? true : false;
                document.getElementById("div_outer_round_formset_" + i).style.display = enabled ? "block" : "none";
            }
        }

        // Updates the non-editable winner score value
        function roundScoreCallback(e) {
            value = parseInt(e.target.value)
            winner_elem = document.getElementById(e.target.id.replace("loser", "winner"))
            winner_elem.value = value < 10 ? 11 : value + 2
        }

        // There isn't a standard Django Widget that would provide the same look, so instead
        // an additional button drives changing the value of th actual form input that is hidden.
        function winnerButtonCallback(e) {
            button = e.target
            input = document.getElementById(button.id.replace("_button", ""))
            input.value = (input.value === "false")
            updateRoundFormWithWinner(input)
        }

        function updateRoundFormWithWinner(input) {
            button = document.getElementById(input.id + "_button")
            if (input.value === "true") {
                button.textContent = "WON"
                button.style.background='#ffffff';
                button.style.color='#000000';
            } else {
                button.textContent = "LOST"
                button.style.background='#000000';
                button.style.color='#ffffff';
            }
        }

        function initForm() {
            document.getElementById("id_round_count").addEventListener("change", roundsCallback);
            for (let i = 0; i < MAX_ROUNDS_PER_MATCH; i++) {
                document.getElementById("id_rounds-" + i + "-score_loser").addEventListener("change", roundScoreCallback);
                winner_button = document.getElementById("id_rounds-" + i + "-player_1_won_button")
                winner_input = document.getElementById("id_rounds-" + i + "-player_1_won")
                winner_button.addEventListener("click", winnerButtonCallback);
                // We cannot rely on the inital value always being "WON" since the form might
                // have been POSTed and then returned to the user following a failed validation.
                updateRoundFormWithWinner(winner_input)
            }
            roundsCallback()
        }
        window.addEventListener("load",initForm);
    </script>
{% endblock %}

gauntlet/templates/matches/new_freeplay.html
{% extends 'matches/new_base.html' %}
{% load crispy_forms_tags %}

{% block match_headline %}
    <h2>Freeplay Match</h2>
{% endblock %}

{% block players %}
    {% crispy opponent_form %}
{% endblock %}

gauntlet/templates/matches/new_tournament.html
{% extends 'matches/new_base.html' %}
{% load crispy_forms_tags %}

{% block match_headline %}
    <h2>Tournament Match - {{ planned_match.tournament.name }}</h2>
{% endblock %}

{% block players %}
    <div id="div_id_opponent" class="mb-3 row">
        <label for="id_opponent" class="col-form-label col-sm-4 col-lg-2 requiredField">
            Opponent
        </label>
        <div class="col-sm-8 col-lg-4">{{opponent}}</div>
    </div>
{% endblock %}

gauntlet/templates/matches/scores.html
{% extends 'base.html' %}

{% block content %}

<div class="card-deck">
{% for matchset in matchsets %}
    {% if matchset.matches.count > 0 %}
        <h2>{{matchset.name}}</h2>
        {% for match in matchset.matches %}
            <div class="card my-2 row col-lg-6">
                <div class="card-body">
                    <table class="table w-auto" id="matches_list">
                    <thead="">
                    <tr>
                        <th class="col">{{ match.date }}</th>
                        <th class="col">M</th>
                        {% for score in match.round_scores %}
                        <th class="col">R{{forloop.counter}}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="col">{{ match.player_1 }}</td>
                            <td class="col">{{ match.score_player_1 }}</td>
                        {% for score in match.round_scores %}
                            <td class="col">{{ score.0 }}</td>
                        {% endfor %}
                        </tr>
                        <tr>
                            <td class="col">{{ match.player_2 }}</td>
                            <td class="col">{{ match.score_player_2 }}</td>
                        {% for score in match.round_scores %}
                            <td class="col">{{ score.1 }}</td>
                        {% endfor %}
                        </tr>
                    </tbody>
                    </table>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endfor %}
</div>
{% endblock %}

gauntlet/templates/matches/tournament_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" media="all">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <h1>{{tournament.name}}</h1>
    {% if tournament.description %}
        <p>{{tournament.description}}</p>
    {% endif %}
    <hr>

    {% if not tournament.isInPlanning %}
        {% if matches_planned_for_user %}
            <h2>Your upcoming matches</h2>
                    <table class="table w-auto" id="matches_list">
                        <tbody>
                        {% for match in matches_planned_for_user %}
                            <tr>
                                <td class="col">
                                {% if match.player_1 == user %}
                                    {{ match.player_2 }}
                                {% else %}
                                    {{ match.player_1 }}
                                {% endif %}
                                </td>
                                <td class="col">
                                    <a href="{% url 'matches:new_planned' id=match.id %}" class="btn btn-info" role="button">Enter score</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
        {% endif %}

        {% if leaderboard_html %}
            <h2>Leaderboard:</h2>
            {% autoescape off %}{{ leaderboard_html }}{% endautoescape %}
        {% endif %}

        {% if scoreboard_html %}
        <h2>Scoreboard:</h2>
            <div>
                {% autoescape off %}{{ scoreboard_html }}{% endautoescape %}
                <div>Legend: [row]:[colum]</div>
            </div>
        {% endif %}
    {% else %}
        <p>Number of signed up players: {{ tournament.players.count}}</p>
        {% if user in tournament.players.all %}
            <p>You are signed up for this event. Please wait until it has started.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" name="withdraw" value="Withdraw" />
            </form>
        {% else %}
            <p>Sign up to play once the tournament has started.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" name="sign_up" value="Sign up" />
            </form>
        {% endif %}

        {% if user.is_superuser %}
            <hr/>
            <h4>Admin:</h4>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" name="start" value="Start the tournament" />
            </form>
        {% endif %}
    {% endif %}
{% endblock %}

gauntlet/templates/matches/tournaments.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" media="all">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <h2>Tournaments</h2>
    {% for tournament in tournament_list %}
        <div class="card my-2 row col-lg-6">
            <div class="card-body">
                <h4>{{tournament.name}}</h4>
                {% if tournament.description %}
                    <p>{{tournament.description}}</p>
                {% endif %}
                <hr/>
                <a href="{% url 'matches:tournament-detail' pk=tournament.pk %}" class="btn btn-info" role="button">See details</a>
            </div>
        </div>
    {% endfor %}
    {% endblock %}