config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gauntlet.users.urls", namespace="users")),
    path("matches/", include("gauntlet.matches.urls", namespace="matches")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gauntlet/matches/urls.py
from django.urls import path

from gauntlet.matches.views import TournamentDetailView, TournamentListView, new_freeplay, new_planned, show_scores

app_name = "matches"

urlpatterns = [
    path("new/freeplay/", new_freeplay, name="new_freeplay"),
    path("new/planned/<int:id>/", new_planned, name="new_planned"),
    path("scores/", show_scores, name="show_scores"),
    path("tournaments/", TournamentListView.as_view(), name="tournaments"),
    path("tournaments/<int:pk>/", TournamentDetailView.as_view(), name="tournament-detail"),
]

gauntlet/users/urls.py
from django.urls import path

from gauntlet.users.views import user_redirect_view

app_name = "users"
urlpatterns = []

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<int:pk>/", view=user_detail_view, name="detail"),
]

gauntlet/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from gauntlet.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Gauntlet.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = models.EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

    def __str__(self):
        return self.email.split("@")[0]

gauntlet/matches/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Match

User = get_user_model()

MAX_ROUNDS_PER_MATCH = 8
INITIAL_ROUNDS_PER_MATCH = 5
MIN_ROUND_SCORE = 11


class BasePartialForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True

        # TODO move styling out of backend code
        self.helper.form_style = "inline"
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-sm-4 col-lg-2"
        self.helper.field_class = "col-sm-8 col-lg-4"
        self.helper.css_class = "border border-secondary rounded p-3 my-3 col-md-6"


class DateForm(BasePartialForm):
    date = forms.DateField(initial=timezone.now, required=True)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get("date") > timezone.now().date():
            raise ValidationError(["You cannot add a match played in the future"])
        return cleaned_data


class OpponentForm(BasePartialForm):
    opponent = forms.ModelChoiceField(queryset=User.objects.order_by("email"), required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields["opponent"].queryset = User.objects.order_by("email").exclude(id=self.user.id)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data["opponent"] == self.user:
            raise ValidationError(["You cannot play against yourself"])
        return cleaned_data


class RoundCountForm(BasePartialForm):
    round_count = forms.IntegerField(
        min_value=1, max_value=MAX_ROUNDS_PER_MATCH, required=False, initial=INITIAL_ROUNDS_PER_MATCH
    )

    def save(self, score_player_1, score_player_2, round_scores):
        data = self.clean()
        if data["player_1"].email < data["player_2"].email:
            match = Match(
                player_1=data["player_1"],
                player_2=data["player_2"],
                score_player_1=score_player_1,
                score_player_2=score_player_2,
                round_scores=round_scores,
                date=data["date"],
            )
        else:
            match = Match(
                player_1=data["player_2"],
                player_2=data["player_1"],
                score_player_1=score_player_2,
                score_player_2=score_player_1,
                round_scores=[list(reversed(r)) for r in round_scores],
                date=data["date"],
            )
        match.save()
        return match


class BaseRoundFormSet(forms.BaseFormSet):
    # The returned scores assume player_1 is the active user,
    # unless reverse was set to True.
    def get_scores(self, round_count, reverse=False):
        def calculate_winner_score(loser_score):
            if loser_score < 10:
                return 11
            return loser_score + 2

        if any(self.errors):
            return
        scores = {
            "player_1": 0,
            "player_2": 0,
            "rounds": [],
        }
        print(round_count)
        for i in range(round_count):
            form = self.forms[i]
            score_loser = form.cleaned_data["score_loser"]
            player_1_won = form.cleaned_data["player_1_won"]
            if (player_1_won and not reverse) or (not player_1_won and reverse):
                scores["player_1"] += 1
                scores["rounds"].append([calculate_winner_score(score_loser), score_loser])
            else:
                scores["player_2"] += 1
                scores["rounds"].append([score_loser, calculate_winner_score(score_loser)])
        return scores


class RoundForm(forms.Form):
    player_1_won = forms.BooleanField(required=False)
    score_loser = forms.IntegerField(min_value=0, max_value=100, label="Loser score")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Field("player_1_won", type="hidden"),
            Field("score_loser"),
        )
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-3"
        self.helper.field_class = "col-9"
        self.initial["player_1_won"] = "true"

    def get_formset_factory():
        # TODO this creates the max amount of round forms, which are then conditionally
        # hidden on the frontend. Rather, the frontend should dynamically create and delete
        # forms as necessary
        return forms.formset_factory(
            RoundForm,
            formset=BaseRoundFormSet,
            extra=MAX_ROUNDS_PER_MATCH,
            min_num=1,
            max_num=MAX_ROUNDS_PER_MATCH,
            absolute_max=MAX_ROUNDS_PER_MATCH,
            validate_min=True,
            validate_max=True,
        )

gauntlet/matches/views.py
import django.shortcuts as shortcuts
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin

from .forms import DateForm, OpponentForm, RoundCountForm, RoundForm
from .models import Match, PlannedMatch, Tournament

User = get_user_model()

MAX_ROUNDS_PER_MATCH = 8
MAX_OWN_MATCHES = 10
MAX_OTHERS_MATCHES = 3


@login_required
def show_scores(request):
    others_matches = Match.objects.without_player(request.user).order_by("-date", "-pk")[:MAX_OTHERS_MATCHES]
    own_matches = Match.objects.with_player(request.user).order_by("-date", "-pk")[:MAX_OWN_MATCHES]
    matchsets = []
    matchsets.append({"name": "Last matches", "matches": others_matches})
    matchsets.append({"name": "Your matches", "matches": own_matches})
    return TemplateResponse(request, "matches/scores.html", {"matchsets": matchsets})


@login_required
def new_freeplay(request):
    if request.method == "POST":
        date_form = DateForm(request.POST, request.FILES)
        opponent_form = OpponentForm(request.POST, request.FILES, user=request.user)
        round_count_form = RoundCountForm(request.POST, request.FILES)
        rounds_formset = RoundForm.get_formset_factory()(request.POST, request.FILES, prefix="rounds")
        if (
            date_form.is_valid()
            and opponent_form.is_valid()
            and round_count_form.is_valid()
            and rounds_formset.is_valid()
        ):
            round_count = round_count_form.cleaned_data["round_count"]
            scores = rounds_formset.get_scores(round_count)
            match = Match(
                date=date_form.cleaned_data["date"],
                player_1=request.user,
                player_2=opponent_form.cleaned_data["opponent"],
                score_player_1=scores["player_1"],
                score_player_2=scores["player_2"],
                round_scores=scores["rounds"],
            )
            match.save()
            return shortcuts.redirect("matches:show_scores")
    else:
        date_form = DateForm()
        opponent_form = OpponentForm(user=request.user)
        round_count_form = RoundCountForm()
        rounds_formset = RoundForm.get_formset_factory()(prefix="rounds")

    return TemplateResponse(
        request,
        "matches/new_freeplay.html",
        {
            "date_form": date_form,
            "opponent_form": opponent_form,
            "round_count_form": round_count_form,
            "rounds_formset": rounds_formset,
        },
    )


@login_required
def new_planned(request, id):
    planned_match = shortcuts.get_object_or_404(PlannedMatch, id=id)
    if planned_match.actual_match is not None:
        # This planned match already has an outcome
        raise Http404

    if request.method == "POST":
        date_form = DateForm(request.POST, request.FILES)
        round_count_form = RoundCountForm(request.POST, request.FILES)
        rounds_formset = RoundForm.get_formset_factory()(request.POST, request.FILES, prefix="rounds")
        if date_form.is_valid() and round_count_form.is_valid() and rounds_formset.is_valid():
            round_count = round_count_form.cleaned_data["round_count"]
            scores = rounds_formset.get_scores(round_count, reverse=(request.user == planned_match.player_2))
            match = Match(
                date=date_form.cleaned_data["date"],
                player_1=planned_match.player_1,
                player_2=planned_match.player_2,
                score_player_1=scores["player_1"],
                score_player_2=scores["player_2"],
                round_scores=scores["rounds"],
            )
            match.save()
            planned_match.actual_match = match
            planned_match.save()
            return shortcuts.redirect("matches:tournament-detail", pk=planned_match.tournament.pk)
    else:
        date_form = DateForm()
        round_count_form = RoundCountForm()
        rounds_formset = RoundForm.get_formset_factory()(prefix="rounds")

    if request.user == planned_match.player_1:
        opponent = planned_match.player_2
    else:
        opponent = planned_match.player_1

    return TemplateResponse(
        request,
        "matches/new_tournament.html",
        {
            "date_form": date_form,
            "round_count_form": round_count_form,
            "rounds_formset": rounds_formset,
            "planned_match": planned_match,
            "opponent": opponent,
        },
    )


@method_decorator(login_required, name="dispatch")
class TournamentListView(ListView):
    queryset = Tournament.objects.order_by("-id")
    template_name = "matches/tournaments.html"


@method_decorator(login_required, name="dispatch")
class TournamentDetailView(SingleObjectMixin, View):
    model = Tournament
    template_name = "matches/tournament_details.html"

    def post(self, request, *args, **kwargs):
        tournament = self.get_object()
        user_in_tournament = request.user in tournament.players.all()

        if "withdraw" in request.POST and user_in_tournament:
            tournament.removePlayer(request.user)
        elif "sign_up" in request.POST and not user_in_tournament:
            tournament.addPlayer(request.user)
        # TODO this should be done via Admin interface instead
        elif "start" in request.POST and request.user.is_superuser:
            tournament.start()

        return self.details(request)

    def get(self, request, *args, **kwargs):
        return self.details(request)

    def details(self, request):
        tournament = self.get_object()

        if tournament.isInPlanning():
            return TemplateResponse(
                request,
                self.template_name,
                {"tournament": tournament},
            )

        scoreboard_df, leaderboard_df = tournament.get_boards()
        # TODO move styling out of backend code
        table_classes = "table table-striped table-bordered table-responsive"
        table_classes_rotated_header = table_classes + " vrt-header"
        scoreboard_html = scoreboard_df.to_html(classes=table_classes_rotated_header)
        leaderboard_html = leaderboard_df.to_html(classes=table_classes)
        matches_planned_for_user = tournament.planned_matches.with_player(request.user).not_played()
        return TemplateResponse(
            request,
            self.template_name,
            {
                "tournament": tournament,
                "matches_planned_for_user": matches_planned_for_user,
                "scoreboard_html": scoreboard_html,
                "leaderboard_html": leaderboard_html,
            },
        )

gauntlet/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

gauntlet/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import RedirectView

User = get_user_model()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

gauntlet/templates/base.html
{% load static i18n %}{% load render_bundle from webpack_loader %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Gauntlet{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A platform for organising social sports events and tracking one's results.">
    <meta name="author" content="Marcin Maciejewski">

    <link rel="icon" href="{% static 'images/favicons/glove_favicon.png' %}">
    <script src="https://kit.fontawesome.com/c769ad4c9d.js" crossorigin="anonymous"></script>

    {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
    <!-- This file stores project-specific CSS -->
    {% render_bundle 'project' 'css' %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      {% render_bundle 'vendors' 'js' attrs='defer' %}

      <!-- place project specific Javascript in this file -->
      {% render_bundle 'project' 'js' attrs='defer' %}

    {% endblock javascript %}

  </head>

  <body class="d-flex flex-column h-100 p-0">

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a href="{% url 'home' %}"><img alt="Home" src={% static 'images/icons8-hockey-glove-50.png' %}></a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'matches:tournaments' %}">Tournaments</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'matches:new_freeplay' %}">Freeplay</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'matches:show_scores' %}">See scores</a>
              </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    <footer
              class="text-center text-lg-start text-white mt-2"
              style="background-color: #3e4551"
              >
        <div
            class="text-center p-3"
            style="background-color: rgba(0, 0, 0, 0.2)"
            >
          © 2024 Copyright: Marcin Maciejewski |
          Built with <a href="https://github.com/cookiecutter/cookiecutter-django/">Cookiecutter Django</a>
          | <a href="https://icons8.com/icon/WIHhUgmcoIyB/hockey-glove">Glove</a> icon by <a href="https://icons8.com">Icons8</a>
          | Source code: <a href="https://github.com/mmacieje/gauntlet/" role="button"><i class="fa-brands fa-github fa"></i></a><a href="https://gitlab.com/mmacieje/gauntlet/" role="button"><i class="fa-brands fa-gitlab fa"></i></a>
        </div>
        <!-- Copyright -->
    </footer>
    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>